growth-ring/taskgrow

app-server/src/main/java/com/growth/task/task/dto/TaskAddRequest.java

- `2023-08-30` 형태로 생성 api 요청시, `LocalDateTime` 형태가 아니라 오류 발생
- LocalDateTime 형식이면 `2023-08-30T00:00:00` 형태로 데이터가 날아와야 함
- `TaskDate`의 의미는 그 테스크의 날짜만을 의미하기 때문에 시간을 받을 필요가 없다. 
- 따라서 `2023-08-30` 형태로 받고 뒤에 시간은 시작 시간으로 파싱해서 넣도록 한다.

날짜 등록시 년월일 형태로 받아서 LocalDateTime 형태로 변환하라

---

app-server/src/main/java/com/growth/task/task/repository/TasksRepositoryCustom.java
app-server/src/main/java/com/growth/task/task/repository/impl/TasksRepositoryCustomImpl.java
app-server/src/main/java/com/growth/task/task/service/TaskListService.java
app-server/src/test/java/com/growth/task/task/controller/TaskListControllerTest.java
app-server/src/test/java/com/growth/task/task/repository/impl/TasksRepositoryCustomImplTest.java
app-server/src/test/java/com/growth/task/task/service/TaskListServiceTest.java

- 리스트 조회 후 `taskDate` 기준으로 정렬 
- 리스트 조회시, `userId`, `startDate`, `endDate`를 넘기는 것이 아니라 TaskListRequest를 넘기도록 수정

테스크 리스트 조회를 리팩토링하라

---

app-server/src/main/java/com/growth/task/user/exception/UserNotFoundException.java
app-server/src/main/java/com/growth/task/user/service/UserService.java

- `UserNotFoundException`이 Task 패키지에 위치하고 있어 User 패키지로 이동

사용자 관련 예외를 사용자 패키지로 옮겨라

---

app-server/src/main/java/com/growth/task/pomodoro/controller/PomodoroUpdateController.java
app-server/src/main/java/com/growth/task/pomodoro/dto/response/PomodoroUpdateResponse.java
app-server/src/main/java/com/growth/task/todo/controller/TodoAddController.java
app-server/src/main/java/com/growth/task/todo/controller/TodoDeleteController.java
app-server/src/main/java/com/growth/task/todo/controller/TodoListController.java
app-server/src/main/java/com/growth/task/todo/controller/TodoUpdateController.java
app-server/src/main/java/com/growth/task/todo/dto/composite/TodoAndPomodoroAddResponse.java
app-server/src/main/java/com/growth/task/todo/dto/request/TodoUpdateRequest.java
app-server/src/main/java/com/growth/task/todo/dto/response/TodoListResponse.java
app-server/src/main/java/com/growth/task/todo/dto/response/TodoUpdateResponse.java

본 PR에서는 다음 변경 사항들을 반영하였습니다:
1. Todo 삭제 API 의 메서드를 POST 에서 DELETE 로 변경하였습니다.
2. TodoAndPomodoroAddResponse 에서 불필요한 메서드를 삭제하였습니다.
3. 사용하지 않는 import 문을 제거하였습니다.
4. `@JsonProperty` 로 직접 정의하던 필드명을 `@JsonNaming` 을 사용하여 snake_case 로 통일하였습니다.
5. Todo 및 Pomodoro API 문서화를 위해 @Tag 애노테이션을 추가하여 설명 및 태그명을 명시하였습니다.
리뷰 부탁드립니다.

Todo 및 Pomodoro API 리팩토링 및 문서화를 개선하라

---

app-server/src/main/java/com/growth/task/pomodoro/domain/Pomodoros.java
app-server/src/test/java/com/growth/task/todo/controller/TodoDeleteControllerTest.java

- 오류 해결을 위해 Todos 와의 연관 관계에 CASCADE 삭제 전략을 적용하였습니다.
- Todo 삭제 API 호출에 대한 테스트 작성했습니다.

Pomodoros 엔터티의 연관 관계 삭제 전략을 추가하라

---

app-server/src/main/java/com/growth/task/review/controller/ReviewUpdateController.java
app-server/src/main/java/com/growth/task/review/domain/Review.java
app-server/src/main/java/com/growth/task/review/dto/ReviewUpdateRequest.java
app-server/src/main/java/com/growth/task/review/service/ReviewUpdateService.java
app-server/src/test/java/com/growth/task/review/controller/ReviewUpdateControllerTest.java
app-server/src/test/java/com/growth/task/review/domain/ReviewTest.java
app-server/src/test/java/com/growth/task/review/service/ReviewUpdateServiceTest.java

issue no. #135 
회고를 수정한다. 
PUT 요청으로 내용과 기분점수를 수정한다. 
PUT 방식이기 때문에, 내용만 수정할 때는 수정된 내용과 기존의 기본점수를 요청에 담아 넘겨야한다.

[Backend] 회고를 수정할 수 있다 #135

---

.gitignore

queryDsl 설정 Path가 적용되지 않아 
path 앞에 **를 붙이는 것으로 수정

gitignore의 queryDSL path를 수정하라

---

app-client/src/components/Review/UserReview.tsx
app-client/src/services/review.ts

issue no. #164 
회고 미입력시 삭제 버튼이 뜨지 않도록 수정했습니다.

[Frontend] 회고 아무것도 입력 안한 상태에서 삭제 누르면 에러메시지가 뜸

---

.github/workflows/client-CI.yml

pull request에 app-client 경로가 포함되어서 CD가 돔.
따라서, push의 경우에만 빌드 되도록 해당 path를 제거

push에만 action이 돌도록 pull request에서 client path를 제거하라

---

app-client/src/components/Pomodoro/Pomodoro.tsx
app-client/src/components/Pomodoro/Timer.tsx
app-client/src/pages/TodosPage/index.tsx

issue no. #165 
기존에는 
- 타이머 : `setInterval`함수 이용한 호출 스케일링
- 뽀모도로 : `requestAnimationFrame`함수 이용
**버그 구현 방법**
뽀모도로 시작후 타이머가 어느순간부터 1초가 2~3초씩 느려짐
뽀모도로가 끝나면 타이머가 제상태로 돌아옴
**버그 발생 원인**
`setInterval`은 지연 간격을 보장되지 않아 정확도가 떨어짐
함수를 실행시키는데  소모되는 시간이 명시한 지연 간격보다 길 때 실행이 종료될 때까지 기다려줌
**해결 방법**
우선 빠르게 대응하고자 타이머도 `requestAnimationFrame`함수를 이용하여 밀림 현상 방지

[Frontend] 타이머 시간이 제대로 작동하도록 하라

---

.gitignore
app-server/src/main/resources/application-dev.yml

issue no. #187
디비 설정 정보를 따로 설정 파일로 빼놓고 git에 올라가지 않도록 처리. 
인스턴스 인바운드 규칙은 앱에서 접근할 때 문제로 인해 일단 ssh 접속만 막아두고 나머진 열어두었다.

[Backend] 디비 비번 빼놓기#187

---

.github/workflows/server-CI.yml
app-server/src/main/resources/application-dev.yml

자동 CI 배포시 DB 접속 에러 문제가 발생 
정확한 원인은 아직 파악이 안됐다.
에러 메세지로 봤을때는 권한 문제인거 같아서 새로운 계정을 만들고 그 계정으로 접속하도록 변경. 
그 후에도 되지 않아서 빌드 파일을 제거하고 `bootjar`로 다시 재 빌드 후 배포하니 성공 
CI 명령어가 원래 assemble 이었으나 build로 수정 bootJar는 테스트 실행, 코드 적용 범위, 정적 코드 분석, 수명주기 check 등을 하지 않기때문에 build로 결정 
이 때문에 안되기도 한다고 하는데 DB연결과 무슨 상관인지...

[Backend] 배포시 DB 접속 에러 문제

---

app-server/src/main/java/com/growth/task/mypage/controller/MyPageController.java
app-server/src/main/java/com/growth/task/review/dto/ReviewDetailWithTaskDateResponse.java
app-server/src/main/java/com/growth/task/review/dto/ReviewListRequest.java
app-server/src/main/java/com/growth/task/review/repository/ReviewRepositoryCustom.java
app-server/src/main/java/com/growth/task/review/repository/impl/ReviewRepositoryCustomImpl.java
app-server/src/main/java/com/growth/task/review/service/ReviewListService.java
app-server/src/main/java/com/growth/task/todo/dto/TodoListRequest.java
app-server/src/test/java/com/growth/task/mypage/controller/MyPageControllerTest.java
app-server/src/test/java/com/growth/task/review/repository/ReviewRepositoryTest.java
app-server/src/test/java/com/growth/task/review/service/ReviewListServiceTest.java
app-server/src/test/java/com/growth/task/todo/application/TodoListServiceTest.java

issue no. #216 
`/api/v1/mypage/{user_id}/review` 
request param 
- `feelings_score` : 감정 점수
- `start_date` : 시작 날짜
- `end_date` : 마지막 날짜 
response 
- `review_id` : 회고 아이디
- `subject` : 회고 제목
- `feelings_score` : 기분 점수
- `task_date` : 회고 날짜 
- 페이징 정보

[Backend] 사용자 감정 통계 상세 리스트를 조회하라

---

app-server/src/main/java/com/growth/task/todo/application/TodoListService.java
app-server/src/main/java/com/growth/task/todo/dto/TodoListRequest.java
app-server/src/main/java/com/growth/task/todo/repository/TodosRepositoryCustom.java
app-server/src/main/java/com/growth/task/todo/repository/impl/TodosRepositoryCustomImpl.java
app-server/src/test/java/com/growth/task/mypage/controller/MyPageControllerTest.java
app-server/src/test/java/com/growth/task/todo/application/TodoListServiceTest.java
app-server/src/test/java/com/growth/task/todo/repository/TodosRepositoryTest.java

issue no. #240
투두 통계 세부 리스트 조회시 날짜 조건을 받아, 날짜 범위 내의 리스트만 가져오도록 한다

[Backend] 투두 통계 세부 리스트 파라미터 조건에 날짜를 추가하라

---

app-server/src/main/java/com/growth/task/review/dto/ReviewListRequest.java
app-server/src/main/java/com/growth/task/review/repository/ReviewRepositoryCustom.java
app-server/src/main/java/com/growth/task/review/repository/impl/ReviewRepositoryCustomImpl.java
app-server/src/main/resources/schema.sql
app-server/src/test/java/com/growth/task/mypage/controller/MyPageControllerTest.java
app-server/src/test/java/com/growth/task/review/repository/ReviewRepositoryTest.java
app-server/src/test/java/com/growth/task/review/service/ReviewListServiceTest.java

issue no. #247
감정은 범위로 조회해야하기 때문에, 조건 조회를 in 절로 변경 
파라미터도 여러개를 받을 수 있도록 리스트로 타입 변경

[Backend] 감정 통계 세부 리스트 조회시 감정 점수를 리스트로 받아 조회하라

---

app-client/src/components/Pomodoro/Pomodoro.tsx
app-client/src/components/Pomodoro/Timer.tsx
app-client/src/pages/TodosPage/index.tsx

기존: 할 일이 끝난 후 끝났다는 화면 표시
변경 후: 할 일이 끝난 후 휴식 화면으로 전환

[Frontend] 할 일 25분 지난 후 휴식으로 화면 전환으로 변경하라

---

app-client/src/components/Todos/Todo.tsx
app-client/src/components/Todos/TodoList.tsx

#281 
기존에는 
선택된 할 일의 텍스트만 파란색으로 보이도록 했었다.
**하지만 색깔만으로 표시하는건 좋지 않다.
색약이 있으신 분들은 구별하기 어렵기 때문이다.**
그래서 색깔말고도 구분되는 걸 추가하기 위해 border로도 추가로 표시하여 모양과 색깔 모두로 구분 될 수 있도록 개선함.

[Frontend] 선택한 할 일 박스 바깥에 border로 표시하라

---

app-client/src/components/Todos/AddTodo.tsx

아무 할 일을 입력하지 않고 엔터를 누르면, 입력해야 된다고 뜨지만 + 버튼을 누르면 아무 텍스트가 없는 할 일이 등록이 됨
+ 버튼을 누르면 무조건 추가되는 현상, 빈 칸이 추가되는 현상은 alert창으로 '할 일을 입력해주세요' 창이 뜨고 추가되지 않도록 수정했습니다.

[Frontend] 빈 칸은 할 일 추가될 수 없도록 하라

---

app-client/src/pages/TodosPage/index.tsx
app-client/src/utils/resetTimer.ts

기존에는 할 일이 선택된 상태에서 새로운 할 일을 선택하면 선택한 할 일이 리셋되는 현상이 있다.
task가 달라졌을 때랑 todoChange가 발생했을 때랑 useEffect 다르게 처리

[Frontend] 할 일이 선택된 상태에서 새로운 할 일을 추가하면 선택된 할 일이 유지되도록 하라

---

app-client/src/components/Todos/Todo.tsx

커서 영역 불확실한 현상 수정
글씨 바깥에 마우스를 가져다 대면 누룰 수 있는 것처럼 나오는데 눌러도 아무런 반응이 없음.
정확히 텍스트 영역을 눌러야 클릭이 됨
텍스트 외의 영역은 커서 비활성화로 수정

[Frontend] 할 일 텍스트 위에만 커서 활성화하라

---

app-client/src/components/UI/Modal.tsx

#297 
닫기 버튼이 너무 우측상단에 위치해있어서 디자인상 좋지 않음
상단, 우측에 여백 부여

[Frontend] 로그인, 회원가입 모달창 닫기 버튼 위치 변경하라

---

app-client/src/components/Todos/AddTodo.tsx
app-client/src/components/Todos/TodoDetail.tsx

기존 : 뽀모도로는 최대 20개까지 가능합니다
변경 후: 계획 뽀모도로는 최대 20개까지 가능합니다
와 같이 '뽀모도로'로 안내되어 있는 텍스트를 '계획 뽀모도로'로 구체화해서 변경

[Frontend] 계획 뽀모도로라고 대상 구체화하여 안내하라

---

app-server/src/main/java/com/growth/task/category/exception/CategoryNotFoundException.java
app-server/src/main/java/com/growth/task/category/service/CategoryRetrieveService.java
app-server/src/main/java/com/growth/task/todo/application/TodoCategoryAddService.java
app-server/src/main/java/com/growth/task/todo/application/TodoWithRelatedAddService.java
app-server/src/main/java/com/growth/task/todo/domain/TodoCategory.java
app-server/src/main/java/com/growth/task/todo/dto/composite/TodoAndPomodoroAddRequest.java
app-server/src/main/java/com/growth/task/todo/dto/composite/TodoAndPomodoroAddResponse.java
app-server/src/main/java/com/growth/task/todo/dto/request/TodoAddRequest.java
app-server/src/main/java/com/growth/task/todo/repository/TodoCategoryRepository.java
app-server/src/test/java/com/growth/task/todo/application/TodoCategoryAddServiceTest.java
app-server/src/test/java/com/growth/task/todo/application/TodoWithRelatedAddServiceTest.java
app-server/src/test/java/com/growth/task/todo/controller/TodoAddControllerTest.java

투두 생성시 카테고리 Id를 넘기면 카테고리가 저장된다. 
카테고리 id를 넘기지 않으면 카테고리 저장되지 않는다. 
```json 
{
"taskId": 1,
"todo": "인강듣기",
"orderNo": 3,
"categoryId": 1,
"performCount": 0,
"planCount": 3
}
```
- null을 넘김
```json
{
"taskId": 1,
"todo": "인강듣기",
"orderNo": 3,
"categoryId": null,
"performCount": 0,
"planCount": 3
}
```
- 해당 항목을 넘기지 않음
```json
{
"taskId": 1,
"todo": "인강듣기",
"orderNo": 3,
"performCount": 0,
"planCount": 3
}
```
응답에는 카테고리명이 표시된다.
- 카테고리가 있는 경우
```json
{
"todoId": 3,
"taskId": 1,
"todo": "인강듣기",
"status": "READY",
"category": "공부",
"performCount": 0,
"planCount": 3,
"orderNo": 3
}
```
- 카테고리가 없는 경우 
```json
{
"todoId": 3,
"taskId": 1,
"todo": "인강듣기",
"status": "READY",
"category": null,
"performCount": 0,
"planCount": 3,
"orderNo": 3
}
```

[Backend] 투두 생성시 카테고리를 지정할 수 있다

---

app-server/src/main/java/com/growth/task/category/dto/CategoryRequest.java
app-server/src/main/java/com/growth/task/category/exception/CategoryAlreadyExistsException.java
app-server/src/main/java/com/growth/task/category/repository/CategoryRepository.java
app-server/src/main/java/com/growth/task/category/service/CategoryAddService.java
app-server/src/test/java/com/growth/task/category/service/CategoryAddServiceTest.java

issue no. #326 , #325 
카테고리 등록시 공백제거가 안되는 버그 수정
카테고리 등록시 이미 등록된 카테고리 명인 경우 예외 처리
기존에는 DB의 제약 조건으로 예외를 던졌으나, DB에서 해당 카테고리명으로 카테고리를 조회하여 이미 존재하는지 확인한다.

[Backend] 카테고리 등록 버그 수정 및 리팩터링
