growth-ring/taskgrow

app-server/src/main/resources/schema.sql
Task에 `task_date` 컬럼을 추가했습니다. `task_date`는 테스크의 날짜입니다.
=> Task에 task_date 컬럼을 추가하라

app-server/src/main/java/com/growth/task/pomodoro/domain/Pomodoros.java, app-server/src/main/java/com/growth/task/pomodoro/domain/PomodorosRepository.java, app-server/src/main/java/com/growth/task/task/domain/TasksRepository.java, app-server/src/main/java/com/growth/task/todo/domain/Todos.java, app-server/src/main/java/com/growth/task/todo/domain/TodosRepository.java, app-server/src/main/java/com/growth/task/user/domain/UsersRepository.java, app-server/src/main/resources/application.yml, app-server/src/test/java/com/growth/task/user/domain/UsersRepositoryTest.java
Users, Todos, Tasks, Pomodoros의 레파지토리를 생성했습니다.
=> 도메인에 레파지토리를 생성하라 

app-server/src/main/java/com/growth/task/commons/advice/ControllerErrorAdvice.java, app-server/src/main/java/com/growth/task/todo/application/TodosService.java
merge conflict이 제대로 해결이 안되 깨진 부분을 수정했습니다. 
- 중괄호 삭제
- TasksRepository 이동
- (+ 의존성 주입 코드에 final을 추가하여 재할당 금지
=> merge conflict을 해결하라

app-server/src/main/java/com/growth/task/pomodoro/dto/request/PomodoroAddRequest.java, app-server/src/main/java/com/growth/task/pomodoro/dto/response/PomodoroAddResponse.java, app-server/src/main/java/com/growth/task/pomodoro/service/PomodoroService.java, app-server/src/main/java/com/growth/task/todo/application/TodoService.java, app-server/src/main/java/com/growth/task/todo/dto/composite/CompositeAddRequest.java, app-server/src/main/java/com/growth/task/todo/dto/composite/CompositeAddResponse.java, app-server/src/main/java/com/growth/task/todo/dto/request/TodoAddRequest.java, app-server/src/main/java/com/growth/task/todo/dto/response/TodoAddResponse.java, app-server/src/main/java/com/growth/task/todo/repository/TodosRepository.java, app-server/src/test/java/com/growth/task/task/controller/TaskDetailControllerTest.java, app-server/src/test/java/com/growth/task/task/controller/TaskListControllerTest.java, app-server/src/test/java/com/growth/task/task/repository/impl/TasksRepositoryCustomImplTest.java, app-server/src/test/java/com/growth/task/todo/domain/TodosRepositoryTest.java
- todo 패키지 밑에 repository 패키지를 생성하여 TodosRepository 파일을 옮겼습니다.
=> TodosRepository 의 위치를 수정하라

.github/workflows/test-app-server.yml, app-server/src/main/java/com/growth/task/commons/advice/ControllerErrorAdvice.java, app-server/src/main/java/com/growth/task/user/controller/UserController.java, app-server/src/main/java/com/growth/task/user/domain/UsersRepository.java, app-server/src/main/java/com/growth/task/user/dto/UserSignUpRequest.java, app-server/src/main/java/com/growth/task/user/dto/UserSignUpResponse.java, app-server/src/main/java/com/growth/task/user/exception/UserNameDuplicationException.java, app-server/src/main/java/com/growth/task/user/service/UserService.java, app-server/src/test/java/com/growth/task/user/controller/UserControllerTest.java
- name, password를 받아서 회원가입 처리 
- 이름 중복시 CONFLICT(409) 응답
=> 사용자는 이름과 비밀번호로 회원가입할 수 있다

app-server/src/main/java/com/growth/task/task/controller/TaskDeleteController.java, app-server/src/main/java/com/growth/task/task/service/TaskDeleteService.java, app-server/src/main/java/com/growth/task/todo/domain/Todos.java, app-server/src/test/java/com/growth/task/task/controller/TaskDeleteControllerTest.java
테스크 id에 해당하는 테스크와 하위 todo 삭제 
존재하지 않는 id면 404 발생
=> 사용자는 테스크를 삭제할 수 있다

app-server/src/main/java/com/growth/task/task/exception/UserNotFoundException.java, app-server/src/main/java/com/growth/task/user/controller/UserController.java, app-server/src/main/java/com/growth/task/user/domain/UsersRepository.java, app-server/src/main/java/com/growth/task/user/dto/UserGetResponse.java, app-server/src/main/java/com/growth/task/user/service/UserService.java, app-server/src/test/java/com/growth/task/user/controller/UserControllerTest.java
이름으로 사용자를 조회
이름에 해당하는 사용자가 없다면 NOT_FOUND(404) 응답
=> 이름으로 사용자를 조회할 수 있다 

app-server/src/main/java/com/growth/task/commons/advice/ControllerErrorAdvice.java
- `ControllerErrorAdvice`에서 Error를 ResponseEntity로 감싸 응답 
```java
{ "error" : "error message" } 
```
와 response status를 반환
=> Error Message를 ResponseEntity로 감싸라

app-server/src/main/java/com/growth/task/task/domain/Tasks.java, app-server/src/main/java/com/growth/task/task/dto/TaskAddRequest.java, app-server/src/main/java/com/growth/task/task/dto/TaskAddResponse.java, app-server/src/main/java/com/growth/task/task/dto/TaskListResponse.java, app-server/src/main/java/com/growth/task/task/dto/TaskListWithTodoStatusResponse.java, app-server/src/main/java/com/growth/task/task/repository/impl/TasksRepositoryCustomImpl.java, app-server/src/test/java/com/growth/task/task/controller/TaskAddControllerTest.java, app-server/src/test/java/com/growth/task/task/controller/TaskDeleteControllerTest.java, app-server/src/test/java/com/growth/task/task/controller/TaskDetailControllerTest.java, app-server/src/test/java/com/growth/task/task/controller/TaskListControllerTest.java, app-server/src/test/java/com/growth/task/task/repository/impl/TasksRepositoryCustomImplTest.java, app-server/src/test/java/com/growth/task/task/service/TaskAddServiceTest.java, app-server/src/test/java/com/growth/task/task/service/TaskListServiceTest.java, app-server/src/test/java/com/growth/task/todo/domain/TodosRepositoryTest.java
- taskDate의 데이터 타입을 LocalDate로 수정
=> taskDate 타입을 LocalDate로 수정하라

app-server/src/main/java/com/growth/task/pomodoro/domain/Pomodoros.java, app-server/src/main/java/com/growth/task/pomodoro/dto/request/PomodoroUpdateRequest.java, app-server/src/main/java/com/growth/task/pomodoro/dto/response/PomodoroUpdateResponse.java, app-server/src/main/java/com/growth/task/pomodoro/repository/PomodorosRepository.java, app-server/src/main/java/com/growth/task/pomodoro/service/PomodoroService.java, app-server/src/main/java/com/growth/task/todo/application/TodoListService.java, app-server/src/main/java/com/growth/task/todo/application/TodoService.java, app-server/src/main/java/com/growth/task/todo/application/TodoUpdateService.java, app-server/src/main/java/com/growth/task/todo/controller/TodoUpdateController.java, app-server/src/main/java/com/growth/task/todo/domain/Todos.java, app-server/src/main/java/com/growth/task/todo/dto/composite/TodoAndPomodoroUpdateRequest.java, app-server/src/main/java/com/growth/task/todo/dto/composite/TodoAndPomodoroUpdateResponse.java, app-server/src/main/java/com/growth/task/todo/dto/request/TodoUpdateRequest.java, app-server/src/main/java/com/growth/task/todo/dto/response/TodoUpdateResponse.java, app-server/src/test/java/com/growth/task/pomodoro/service/PomodoroServiceTest.java, app-server/src/test/java/com/growth/task/todo/application/TodoListServiceTest.java, app-server/src/test/java/com/growth/task/todo/application/TodoServiceTest.java, app-server/src/test/java/com/growth/task/todo/application/TodoUpdateServiceTest.java
=> Todo 업데이트 기능을 구현하라

app-server/src/main/java/com/growth/task/commons/advice/ControllerErrorAdvice.java, app-server/src/main/java/com/growth/task/task/domain/Tasks.java, app-server/src/main/java/com/growth/task/task/exception/UserAndTaskDateUniqueConstraintViolationException.java, app-server/src/main/java/com/growth/task/task/service/TaskAddService.java, app-server/src/test/java/com/growth/task/task/controller/TaskAddControllerTest.java
=> 사용자의 이미 존재하는 테스크 날짜에 요청이 온 경우 Bad Request를 응답하라

app-client/src/components/User/Login/Login.tsx, app-client/src/components/User/SignUp/SignUp.tsx, app-client/src/pages/MainPage/index.tsx, app-client/src/services/users.ts, app-client/src/store/login.ts, app-client/vite.config.ts, app-server/src/main/generated/com/growth/task/commons/domain/QBaseTimeEntity.java, app-server/src/main/generated/com/growth/task/pomodoro/domain/QPomodoros.java, app-server/src/main/generated/com/growth/task/task/domain/QTasks.java, app-server/src/main/generated/com/growth/task/todo/domain/QTodos.java, app-server/src/main/generated/com/growth/task/user/domain/QUsers.java
=> User API 연동하라

app-server/src/main/java/com/growth/task/pomodoro/controller/PomodoroUpdateController.java, app-server/src/main/java/com/growth/task/pomodoro/dto/response/PomodoroUpdateResponse.java, app-server/src/main/java/com/growth/task/todo/controller/TodoDeleteController.java, app-server/src/main/java/com/growth/task/todo/controller/TodoListController.java, app-server/src/main/java/com/growth/task/todo/controller/TodoUpdateController.java, app-server/src/main/java/com/growth/task/todo/dto/response/TodoListResponse.java, app-server/src/main/java/com/growth/task/todo/dto/response/TodoUpdateResponse.java, app-server/src/test/java/com/growth/task/todo/application/TodoServiceTest.java, app-server/src/test/java/com/growth/task/todo/controller/TodoListControllerTest.java
- 카멜 케이스 형식으로 명명된 변수와 필드의 이름을 스네이크 케이스 형식으로 변환
- TodoUpdateResponse 에서 누락된 응답값을 추가
- 변경된 스네이크 케이스 형식 관련 테스트 수정
=> Todo 서비스에서 사용되는 변수나 필드의 이름을 스네이크 케이스 형식으로 명명하라

app-server/src/main/java/com/growth/task/pomodoro/controller/PomodoroUpdateController.java, app-server/src/main/java/com/growth/task/todo/controller/TodoAddController.java, app-server/src/main/java/com/growth/task/todo/controller/TodoDeleteController.java, app-server/src/main/java/com/growth/task/todo/controller/TodoListController.java, app-server/src/main/java/com/growth/task/todo/controller/TodoUpdateController.java
Swagger 문서에서 API 카테고리별로 분류되도록 테그 지정
=> Swagger Api를 카테코리별로 분류하라

app-server/src/main/java/com/growth/task/commons/advice/ControllerErrorAdvice.java, app-server/src/main/java/com/growth/task/pomodoro/controller/PomodoroUpdateController.java, app-server/src/main/java/com/growth/task/pomodoro/domain/Pomodoros.java, app-server/src/main/java/com/growth/task/pomodoro/exception/PomodoroNotFoundException.java, app-server/src/main/java/com/growth/task/pomodoro/repository/PomodorosRepository.java, app-server/src/main/java/com/growth/task/pomodoro/service/PomodoroService.java, app-server/src/main/java/com/growth/task/todo/domain/Todos.java, app-server/src/test/java/com/growth/task/pomodoro/controller/PomodoroUpdateControllerTest.java, app-server/src/test/java/com/growth/task/pomodoro/service/PomodoroServiceTest.java
해당 API :`/api/v1/pomodoros/{todo_id}/complete`
뽀모도로가 완료되면 perform_count가 1 증가한다. 
- 진행중인 ( status.PROGRESS) 인 뽀모도로가 완료시, perform_count가 1 증가
- 완료(DONE)된 경우 400 에러
- 준비(READY)인 경우 status를 업데이트 한다.
=> 뽀모도로가 완료되면 perform_count가 1 증가한다

app-server/src/main/java/com/growth/task/pomodoro/service/PomodoroService.java, app-server/src/main/java/com/growth/task/todo/domain/Todos.java, app-server/src/test/java/com/growth/task/pomodoro/controller/PomodoroUpdateControllerTest.java, app-server/src/test/java/com/growth/task/pomodoro/service/PomodoroServiceTest.java
#64    
status가 ready인지 체크하고 맞다면 plan_count에 수정을하고, 아니라면  400에러를 응답한다
=> status = ready일 때만, plan_count만 수정이 가능하고 그외 status일때400 에러를 응답하라

app-server/src/main/java/com/growth/task/pomodoro/controller/PomodoroUpdateController.java, app-server/src/main/java/com/growth/task/pomodoro/service/PomodoroAddService.java, app-server/src/main/java/com/growth/task/pomodoro/service/PomodoroUpdateService.java, app-server/src/main/java/com/growth/task/todo/application/TodoAddService.java, app-server/src/main/java/com/growth/task/todo/domain/Todos.java, app-server/src/test/java/com/growth/task/pomodoro/controller/PomodoroUpdateControllerTest.java, app-server/src/test/java/com/growth/task/pomodoro/service/PomodoroAddServiceTest.java, app-server/src/test/java/com/growth/task/pomodoro/service/PomodoroUpdateServiceTest.java, app-server/src/test/java/com/growth/task/todo/application/TodoAddServiceTest.java, app-server/src/test/java/com/growth/task/todo/application/TodoListServiceTest.java
뽀모도로 저장 기능과 업데이트 역할을 분리하여 클래스를 분리
=> 뽀모도로 저장 기능과 업데이트 역할을 분리하여 클래스를 분리하라

app-client/src/components/Calendar/Calendar.css, app-client/src/components/Calendar/Calendar.tsx, app-client/src/components/Todos/DeleteTask.tsx, app-client/src/components/Todos/Header.tsx, app-client/src/components/Todos/HeaderDate.tsx, app-client/src/components/Todos/Todo.tsx, app-client/src/components/Todos/TodoList.tsx, app-client/src/pages/MainPage/index.tsx, app-client/src/pages/TodosPage/index.tsx
**반응형 분기점**
스마트폰: (max-width: 767px)
태블릿 : (min-width: 768px) and (max-width: 1023px)
데스크탑 & 노트북 : (min-width: 1024px)
=> 반응형으로 제작하라

app-client/src/components/Calendar/Calendar.tsx, app-client/src/components/User/Login/Login.tsx, app-client/src/services/users.ts, app-client/src/store/task.ts, app-client/src/store/user.ts
**userName, taskId를 로컬 스토리지에 저장한다.**
새로고침시 유저 아이디가 날라가는 현상을 방지하고자
1. 유저 로그인 > 로컬 스토리지에 유저 아이디 저장
2. 새로고침 > 로컬 스토리지에 유저 아이디 있는지 확인. 유저 아이디가 있다면 가져옴
todo로 넘어갈시 taskId도 필요하다.
1. task에서 특정날짜 선택시 taskId를 저장한다.
2. todo에서 로컬 스토리지에 저장된 taskId를 가져온다.
=> 로컬 스토리지에 유저 정보를 저장해야 한다.

app-client/src/components/Todos/Todo.tsx
이슈NO: #81 
todo 수정 아이콘을 연필로 변경
=> #81 todo 수정 아이콘 변경

app-client/src/components/Pomodoro/Timer.tsx, app-client/src/components/Todos/StateBtn.tsx, app-client/src/components/Todos/Todo.tsx, app-client/src/components/Todos/TodoList.tsx, app-client/src/pages/TodosPage/index.tsx, app-client/src/store/timer.ts, app-client/src/store/todos.ts, app-client/src/utils/resetTimer.ts
=> 뽀모도로 리셋 재설정하라

app-server/src/main/java/com/growth/task/task/dto/TaskTodoDetailResponse.java, app-server/src/main/java/com/growth/task/task/service/TaskDetailService.java, app-server/src/main/java/com/growth/task/todo/application/TodoListService.java, app-server/src/main/java/com/growth/task/todo/repository/TodosRepository.java, app-server/src/main/java/com/growth/task/todo/repository/TodosRepositoryCustom.java, app-server/src/main/java/com/growth/task/todo/repository/impl/TodosRepositoryCustomImpl.java, app-server/src/test/java/com/growth/task/task/controller/TaskDetailControllerTest.java, app-server/src/test/java/com/growth/task/todo/repository/TodosRepositoryTest.java
이슈 no. #85 
/api/v1/tasks/{task_id}/todos
```
{
"task_id": 1,
"todos": [
{todo: "책읽기", ":perform_count":  2 , "plan_count": 5},
{todo: "스터디", ":perform_count":  0 , "plan_count": 3},
]
}
```
=> [Backend] 테스크 미리보기에서 횟수도 같이 보여줘야한다 #85

app-server/src/main/java/com/growth/task/todo/domain/Todos.java, app-server/src/test/java/com/growth/task/task/controller/TaskDetailControllerTest.java, app-server/src/test/java/com/growth/task/task/controller/TaskListControllerTest.java, app-server/src/test/java/com/growth/task/task/repository/impl/TasksRepositoryCustomImplTest.java, app-server/src/test/java/com/growth/task/todo/repository/TodosRepositoryTest.java
issue no. #90 
Todo 글자수를 18자로 제한.
=> [Backend] ToDo 글자수는 18자로 제한한다 #90

app-server/src/main/java/com/growth/task/todo/domain/Todos.java, app-server/src/test/java/com/growth/task/todo/application/TodoServiceTest.java, app-server/src/test/java/com/growth/task/todo/domain/TodosTest.java
issue no. #92  
- todo status가 ready일 때, 완료가 되지 않도록 검증
=> [Backend] status 업데이트 Validation 작업 #92

app-client/src/components/Todos/AddTodos.tsx, app-client/src/components/Todos/TodoDetail.tsx, app-client/src/pages/TodosPage/index.tsx
issue no. #94 
plan_count 개당 20개
todo 글자수 18자 제한
=> [Frontend] plan_count는 개당 20개 todo는 글자수 18자로 제한하라

app-client/src/components/Todos/Todo.tsx, app-client/src/components/Todos/TodoList.tsx, app-client/src/services/todo.ts
issue no. #96 
- todo 완료 설정은 사용자가 done, progress 로 설정 바꿀 수 있다
- todo 완료는 해당 todo의 status가 ready상태면 done으로 설정 바꿀 수 없다
=> [Frontend] todo 완료 설정은 사용자가 바꿀 수 있다

app-server/src/main/java/com/growth/task/todo/application/TodoAddService.java, app-server/src/main/java/com/growth/task/todo/application/TodoService.java
issue no. #99 
기존 todo와 pomodoro쪽 비즈니스 로직에서 트랜잭션 관리가 안되고 있어, 예상대로 동작하지 않는 일이 발생. 
따라서 메소드 단위로 트랜잭션을 걸어줌
=> [Backend] 트랜잭션이 안걸려있는 DB접근 로직에 트랜잭션을 걸어라 #99

app-client/src/components/Calendar/Calendar.tsx, app-client/src/utils/checkTaskExists.ts
issue no. #98 
- hover시 보이는 todo가 길 경우 생략(...)하라 todo 한 줄로 나열하기
- todo 3개 앞에 체크박스로 표시하라
- 기존에 todo만 보이던 것을 todo와 횟수를 같이 보여주도록 변경하라
=> [Frontend] task에서 hover시 보이는 todo를 수정하라

app-server/src/main/java/com/growth/task/todo/repository/impl/TodosRepositoryCustomImpl.java, app-server/src/test/java/com/growth/task/task/controller/TaskDetailControllerTest.java
issue no. #102 
task 미리보기에 task_id 필터 추가
=> [Backend] task 미리보기에 task_id 필터링을 걸어라 #102

app-client/src/components/Calendar/Calendar.tsx, app-client/src/pages/TaskPage/index.tsx, app-client/src/store/task.ts, app-client/src/utils/startEndDate.ts
issue no. #104 
any타입으로 임시 지정되어 있는 타입을 지정하라
=> [Frontend] Type을 지정하라

app-server/Dockerfile, app-server/build.gradle, app-server/src/main/resources/application-dev.yml, app-server/src/main/resources/application.yml
issue no. #108 
Ec2 인스턴스에 docker로 spring-boot 서버를 띄웠다. 
주소 : [https://3.39.23.180:8080](https://3.39.23.180:8080)
=> [Backend] Ec2 spring-boot docker로 띄우기 #108

app-client/Dockerfile, app-client/nginx.conf, app-client/src/services/task.ts, app-client/src/services/todo.ts, app-client/src/services/users.ts, app-server/src/main/resources/schema.sql
- 도커파일에서 빌드 경로 수정 
- nginx 설정에서 빌드 경로
- nginx 설정에서 백엔드 요청 경로 도커 호스트로 변경
- 클라이언트 요청 url에서 httpClient 제거
=> 클라이언트 도커파일과 nginx 설정 파일을 수정하라

app-client/nginx.conf, app-server/src/main/resources/application-dev.yml
=> 인스턴스 호스트를 수정하라

app-client/src/components/Calendar/Calendar.tsx
locale을 넣으면 배포 시 문제 생기고 locale을 빼면 task에서 날짜가 제대로 표시 안되고 Invalid date로 표시되는 현상을 수정하였습니다.
=> [Frontend] task 날짜 오류를 고쳐라

app-server/build.gradle, app-server/src/main/java/com/growth/task/commons/config/SecurityConfig.java, app-server/src/main/java/com/growth/task/todo/controller/TodoAddController.java, app-server/src/main/java/com/growth/task/user/controller/UserController.java, app-server/src/main/java/com/growth/task/user/domain/Users.java, app-server/src/main/java/com/growth/task/user/service/UserService.java, app-server/src/test/java/com/growth/task/pomodoro/service/PomodoroAddServiceTest.java, app-server/src/test/java/com/growth/task/task/service/TaskAddServiceTest.java, app-server/src/test/java/com/growth/task/todo/application/TodoAddServiceTest.java, app-server/src/test/java/com/growth/task/todo/application/TodoServiceTest.java
issue no. #117 
사용자 회원가입시 비밀번호를 암호화하여 저장하도록 수정
=> 사용자 비밀번호를 암호화하여 저장하라

app-server/src/main/java/com/growth/task/user/controller/LoginController.java, app-server/src/main/java/com/growth/task/user/dto/LoginResponse.java
=> 로그인 응답에 id를 추가하라

app-client/nginx.conf, app-server/src/main/java/com/growth/task/user/dto/LoginResponse.java
=> 로그인 유저 응답의 id를 user_id로 수정하라

app-server/src/main/java/com/growth/task/review/domain/Review.java, app-server/src/main/resources/schema.sql
=> [Backend] 회고 테이블 설계 #123

app-server/src/main/java/com/growth/task/review/domain/Review.java, app-server/src/main/resources/schema.sql
하나의 테스크에는 하나의 회고만 달릴 수 있다 
따라서 ManyToOne이 아니라 OneToOne
=> 연관관계를 변경하라

app-client/src/services/users.ts
=> [Frontend] 변경된 로그인 API를 연결하라

app-client/src/components/User/Login/Login.tsx, app-client/src/components/User/SignUp/SignUp.tsx
issue no. #129 
로그인, 회원가입 화면 수정
=> [Frontend] 이름, 비밀번호 필수 입력 조건과 비밀번호 암호화 하라

app-server/src/main/java/com/growth/task/commons/advice/ControllerErrorAdvice.java, app-server/src/main/java/com/growth/task/review/controller/ReviewAddController.java, app-server/src/main/java/com/growth/task/review/domain/Review.java, app-server/src/main/java/com/growth/task/review/dto/ReviewAddRequest.java, app-server/src/main/java/com/growth/task/review/dto/ReviewAddResponse.java, app-server/src/main/java/com/growth/task/review/exception/AlreadyReviewException.java, app-server/src/main/java/com/growth/task/review/exception/OutOfBoundsException.java, app-server/src/main/java/com/growth/task/review/service/ReviewAddService.java, app-server/src/main/java/com/growth/task/review/service/ReviewRepository.java, app-server/src/main/java/com/growth/task/task/service/TaskDetailService.java, app-server/src/test/java/com/growth/task/review/controller/ReviewAddControllerTest.java, app-server/src/test/java/com/growth/task/review/service/ReviewAddServiceTest.java, app-server/src/test/java/com/growth/task/task/service/TaskAddServiceTest.java
issue no. #131 
하루에 하나의 회고를 작성
이미 작성된 회고가 있을 경우 409(Conflict) 
기분 점수는 1~10만 입력할 수 있다. 
그 외의 범위는 400 에러
=> [Backend] 하루에 하나의 회고를 생성할 수 있다 #131

app-server/src/main/java/com/growth/task/commons/advice/ControllerErrorAdvice.java, app-server/src/main/java/com/growth/task/review/controller/ReviewDetailController.java, app-server/src/main/java/com/growth/task/review/dto/ReviewDetailResponse.java, app-server/src/main/java/com/growth/task/review/exception/ReviewNotFoundException.java, app-server/src/main/java/com/growth/task/review/service/ReviewDetailService.java, app-server/src/test/java/com/growth/task/review/controller/ReviewDetailControllerTest.java, app-server/src/test/java/com/growth/task/review/service/ReviewDetailServiceTest.java
issue no. #133 
회고 id에 해당하는 회고를 조회
없다면 404 응답을 준다. 
클라이언트에서는 사용자에게 에러를 보여주는 것이 아니라 작성 화면을 보여준다
=> [Backend] 회고를 조회할 수 있다#133

app-server/src/main/java/com/growth/task/review/controller/ReviewDeleteController.java, app-server/src/main/java/com/growth/task/review/service/ReviewDeleteService.java, app-server/src/test/java/com/growth/task/review/controller/ReviewDeleteControllerTest.java, app-server/src/test/java/com/growth/task/review/controller/ReviewDetailControllerTest.java, app-server/src/test/java/com/growth/task/review/service/ReviewDeleteServiceTest.java
=> [Backend] 회고를 삭제할 수 있다 #136

app-client/src/components/Review/Mood.tsx, app-client/src/components/Review/MoodSelect.tsx, app-client/src/components/Review/Review.tsx, app-client/src/components/Review/SelectedMood.tsx, app-client/src/components/Review/Title.tsx, app-client/src/components/Review/UserReview.tsx, app-client/src/components/Todos/StateBtn.tsx, app-client/src/components/Todos/Todo.tsx, app-client/src/components/UI/Button.tsx, app-client/src/pages/TodosPage/index.tsx, app-client/src/store/review.ts, app-client/src/store/timer.ts, app-client/src/utils/resetTimer.ts
=> [Frontend] todo에서 회고 화면을 구현하라

app-client/src/components/Review/Review.tsx, app-client/src/components/Todos/Header.tsx
issue no. #141 
+ Review에서 컴포넌트명 소문자로 되어있는 부분도 수정
=> [Frontend] todo에서 task로 이동하는 버그를 수정하라

app-server/src/main/java/com/growth/task/review/controller/ReviewDetailController.java, app-server/src/main/java/com/growth/task/review/exception/ReviewNotFoundException.java, app-server/src/main/java/com/growth/task/review/service/ReviewDetailService.java, app-server/src/main/java/com/growth/task/review/service/ReviewRepository.java, app-server/src/test/java/com/growth/task/review/controller/ReviewDetailControllerTest.java, app-server/src/test/java/com/growth/task/review/service/ReviewDetailServiceTest.java
issue. no #144 
review_id로 조회하던 방식에서 task_id 조회로 변경
=> [Backend] 회고 조회시 Task Id로 조회하라 #144

app-server/src/main/java/com/growth/task/review/dto/ReviewAddRequest.java
issue no. #146 
회고 생성 request에서 content -> contents 로 오타 수정
=> [Backend] 회고 내용을 contents로 통일하라 #146

.gitignore, app-server/src/main/java/com/growth/task/review/dto/ReviewAddRequest.java
gitignore 파일에 querydsl 사용시 자동 생성되는 q클래스 패스가 추가되지 않아 git에 걸림
gitignore에 querydsl q클래스 패스를 추가
=> gitignore에 querydsl q클래스 패스를 추가하라

app-server/src/main/java/com/growth/task/task/dto/TaskListQueryResponse.java, app-server/src/main/java/com/growth/task/task/dto/TaskListResponse.java, app-server/src/main/java/com/growth/task/task/repository/TasksRepositoryCustom.java, app-server/src/main/java/com/growth/task/task/repository/impl/TasksRepositoryCustomImpl.java, app-server/src/main/java/com/growth/task/task/service/TaskListService.java, app-server/src/test/java/com/growth/task/task/controller/TaskListControllerTest.java, app-server/src/test/java/com/growth/task/task/repository/impl/TasksRepositoryCustomImplTest.java, app-server/src/test/java/com/growth/task/task/service/TaskListServiceTest.java
=> [Backend] 테스크 화면에서 리스트 응답에 기분점수 값도 포함하라 #151

app-client/src/components/Review/MoodSelect.tsx, app-client/src/components/Review/UserReview.tsx, app-client/src/pages/TodosPage/index.tsx, app-client/src/services/review.ts, app-client/src/store/review.ts, app-server/src/main/java/com/growth/task/task/dto/TaskListQueryResponse.java, app-server/src/main/java/com/growth/task/task/dto/TaskListResponse.java, app-server/src/main/java/com/growth/task/task/repository/TasksRepositoryCustom.java, app-server/src/main/java/com/growth/task/task/repository/impl/TasksRepositoryCustomImpl.java, app-server/src/main/java/com/growth/task/task/service/TaskListService.java, app-server/src/test/java/com/growth/task/task/controller/TaskListControllerTest.java, app-server/src/test/java/com/growth/task/task/repository/impl/TasksRepositoryCustomImplTest.java, app-server/src/test/java/com/growth/task/task/service/TaskListServiceTest.java
=> [Frontend] 회고 API를 연동하라

.github/workflows/server-CI.yml
=> 그래들 권한 설정을 위해 app-server 경로로 이동하라

app-server/src/main/java/com/growth/task/commons/advice/ControllerErrorAdvice.java, app-server/src/main/java/com/growth/task/commons/advice/EntityNotFoundException.java, app-server/src/main/java/com/growth/task/commons/error/ControllerErrorAdvice.java, app-server/src/main/java/com/growth/task/commons/error/ErrorCode.java, app-server/src/main/java/com/growth/task/commons/error/ErrorResponse.java, app-server/src/main/java/com/growth/task/commons/error/exception/AlreadyExistsException.java, app-server/src/main/java/com/growth/task/commons/error/exception/AuthenticationFailureException.java, app-server/src/main/java/com/growth/task/commons/error/exception/BadArgumentException.java, app-server/src/main/java/com/growth/task/commons/error/exception/BadRequestException.java, app-server/src/main/java/com/growth/task/commons/error/exception/BusinessException.java, app-server/src/main/java/com/growth/task/commons/error/exception/EntityNotFoundException.java, app-server/src/main/java/com/growth/task/pomodoro/exception/PomodoroNotFoundException.java, app-server/src/main/java/com/growth/task/review/exception/AlreadyReviewException.java, app-server/src/main/java/com/growth/task/review/exception/OutOfBoundsException.java, app-server/src/main/java/com/growth/task/review/exception/ReviewNotFoundException.java, app-server/src/main/java/com/growth/task/task/exception/UserAndTaskDateUniqueConstraintViolationException.java, app-server/src/main/java/com/growth/task/todo/exception/BadInputParameterException.java, app-server/src/main/java/com/growth/task/todo/exception/TaskNotFoundException.java, app-server/src/main/java/com/growth/task/todo/exception/TodoNotFoundException.java, app-server/src/main/java/com/growth/task/user/exception/AuthenticationFailureException.java, app-server/src/main/java/com/growth/task/user/exception/LoginFailException.java, app-server/src/main/java/com/growth/task/user/exception/UserNameDuplicationException.java, app-server/src/main/java/com/growth/task/user/exception/UserNotFoundException.java, app-server/src/main/java/com/growth/task/user/service/AuthenticationService.java, app-server/src/test/java/com/growth/task/review/controller/ReviewAddControllerTest.java, app-server/src/test/java/com/growth/task/task/controller/TaskAddControllerTest.java, app-server/src/test/java/com/growth/task/user/controller/UserControllerTest.java
issue no. #163 
비즈니스 예외, 커스텀한 예외들을 계층적으로 구조화.
=> [Backend] 에러 핸들링을 공통화하라

app-client/src/services/api.ts, app-client/src/services/review.ts, app-client/src/services/task.ts, app-client/src/services/todo.ts, app-client/src/services/users.ts
issue no. #168 
로컬, 메인 번갈아서 확인하기 편하도록 httpClient 설정
=> [Frontend] httpClient 설정

.gitignore
=> add gitignore .DS_Store

app-client/src/components/Review/MoodSelect.tsx, app-client/src/components/Todos/TodoList.tsx, app-client/src/pages/TodosPage/index.tsx
issue no. #175 
todo에서 왼쪽 화면 업데이트가 안되는 오류 수정
=> [Frontend] todo에서 날짜 변경시 왼쪽 화면이 초기화되어야 한다

README.md
=> 리드미에 해당화면 동작을 추가하라

.gitignore, app-server/src/main/resources/application-dev.yml
디비 패스워드 변경 
디비 설정을 따로 빼두는 것은 테스트 후 적용
=> Change db config

app-server/src/main/java/com/growth/task/todo/domain/Todos.java
status가 string으로 설정이 안되어 있어서 숫자로 입력 되고 있었다. 
따라서, 이를 string설정
=> status를 디비에 String으로 저장되도록 하라

app-client/src/components/Calendar/Calendar.tsx, app-client/src/components/Pomodoro/PomodoroBtn.tsx, app-client/src/components/Todos/DeleteTodo.tsx, app-client/src/components/Todos/Header.tsx, app-client/src/components/Todos/StateBtn.tsx, app-client/src/components/Todos/Todo.tsx, app-client/src/components/Todos/TodoList.tsx, app-client/src/components/UI/Alert.tsx, app-client/src/pages/TodosPage/index.tsx, app-client/src/store/todos.ts, app-client/src/utils/isToday.ts, app-client/src/utils/resetTimer.ts
=> [Frontend] UI/UX 개선

app-server/src/main/java/com/growth/task/todo/application/TodoListService.java, app-server/src/main/java/com/growth/task/todo/controller/TodoListController.java, app-server/src/main/java/com/growth/task/todo/dto/TodoResponse.java, app-server/src/main/java/com/growth/task/todo/dto/TodoStatsRequest.java, app-server/src/main/java/com/growth/task/todo/dto/TodoStatsResponse.java, app-server/src/main/java/com/growth/task/todo/repository/TodosRepositoryCustom.java, app-server/src/main/java/com/growth/task/todo/repository/impl/TodosRepositoryCustomImpl.java, app-server/src/test/java/com/growth/task/todo/application/TodoListServiceTest.java, app-server/src/test/java/com/growth/task/todo/repository/TodosRepositoryTest.java
issue no. #193 
- 사용자 Id(필수)와 날짜 범위(선택)을 받아 처리 
- `/todos/stats/{user_id}?start_date={start_date}&end_date={end_date}` 
- 총 개수, 완료한 개수, 진행중 개수, 미완료 개수를 리턴 
TODO
=> [Backend] ToDo  통계 API 구현 

app-server/src/main/java/com/growth/task/pomodoro/service/PomodoroAddService.java, app-server/src/main/java/com/growth/task/pomodoro/service/PomodoroUpdateService.java
issue no. #201 
Pomodoro 비즈니스 로직의 트랜잭션 Scope를 클래스에서 메소드를 변경
=> 트랜잭션을 클래스에서 메소드로 변경하라

app-client/package-lock.json, app-client/package.json, app-client/src/components/Menu/Header.tsx, app-client/src/components/Menu/Menu.tsx, app-client/src/components/Stats/HeaderDate.tsx, app-client/src/components/Stats/Mood/Chart.tsx, app-client/src/components/Stats/Mood/MoodStats.tsx, app-client/src/components/Stats/Todos/Circle.tsx, app-client/src/components/Stats/Todos/TodosStats.tsx, app-client/src/components/Stats/UI/Box.tsx, app-client/src/components/User/Form.tsx, app-client/src/constants/StatsComment.ts, app-client/src/pages/MyPage/index.tsx, app-client/src/pages/TaskPage/index.tsx, app-client/src/routes/Router.tsx, app-client/src/services/api.ts, app-client/src/store/user.ts
#200 
- task에서 마이페이지 버튼 생성
- 마이페이지 구현 (한 일, 감정)
=> [Frontend] 마이페이지 화면 구현

app-client/src/components/Stats/HeaderDate.tsx, app-client/src/components/Stats/Mood/Chart.tsx, app-client/src/components/Stats/Mood/MoodStats.tsx, app-client/src/constants/StatsComment.ts, app-client/src/pages/MyPage/index.tsx, app-client/src/services/api.ts, app-client/src/services/review.ts, app-client/src/store/mood.ts, app-client/src/store/stats.ts
=> [Frontend] 마이페이지 감정 통계 API를 연동하라

app-client/src/components/Stats/HeaderDate.tsx, app-client/src/components/Stats/Mood/Chart.tsx, app-client/src/components/Stats/Mood/MoodStats.tsx, app-client/src/components/Stats/Todos/Circle.tsx, app-client/src/components/Stats/Todos/TodosStats.tsx, app-client/src/components/Stats/UI/Box.tsx, app-client/src/constants/StatsComment.ts, app-client/src/pages/MyPage/index.tsx
#210 
- 레이아웃 수정
- 날짜헤더 위치 가운데 변경
- 한 일 코멘트 수정
=> [Frontend] CSS 반응형 레이아웃 수정

app-client/src/pages/MyPage/index.tsx, app-client/src/store/mood.ts, app-client/src/store/stats.ts
=> [Frontend] 통계에서 감정 코멘트 실시간 반영과 현재 날짜 초기화 되어야 한다

app-server/src/main/java/com/growth/task/review/dto/ReviewAddRequest.java, app-server/src/main/java/com/growth/task/review/exception/InvalidReviewRequestException.java, app-server/src/main/java/com/growth/task/review/service/ReviewAddService.java, app-server/src/main/java/com/growth/task/todo/repository/TodosRepository.java, app-server/src/test/java/com/growth/task/review/controller/ReviewAddControllerTest.java, app-server/src/test/java/com/growth/task/review/service/ReviewAddServiceTest.java
issue no. #220 
회고 작성시 Todo가 존재하는지 검사하는 validate 추가 
없다면 400을 응답한다
=> [Backend] 회고는 Todo가 하나라도 있어야 작성 가능하다

app-client/src/components/Todos/StateBtn.tsx
=> [Frontend] 회고는 Todo가 하나라도 있어야 작성 가능하다

app-client/src/components/Calendar/Calendar.tsx, app-client/src/components/Calendar/FeelingsScore.tsx
=> [Frontend] task에서 감정 표시가 안 보이는 현상을 수정하라

app-client/src/components/Calendar/FeelingsScore.tsx, app-client/src/components/Stats/Mood/Chart.tsx
미처 지우지 못한 채로 올라간 console.log제거
=> [Frontend] console.log 제거

README.md
프로젝트 기획 배경, 기능, 상세 소개, 기술 스택 추가
=> 리드미 내용을 추가하라

app-client/src/components/Stats/Todos/Circle.tsx, app-client/src/components/Stats/UI/Box.tsx, app-client/src/components/Stats/UI/Detail.tsx, app-client/src/components/Stats/UI/Summary.tsx
#231 
통계 할 일 세부리스트 구현
- 제목 / 뽀모도로 개수
- 타이틀 변경
- 이전 상태로 돌아가기 버튼
=> [Frontend] 통계 할 일 세부 리스트 구현하라

app-server/src/main/java/com/growth/task/todo/application/TodoListService.java, app-server/src/main/java/com/growth/task/todo/controller/TodoListController.java, app-server/src/main/java/com/growth/task/todo/dto/TodoListRequest.java, app-server/src/main/java/com/growth/task/todo/dto/response/TodoDetailResponse.java, app-server/src/main/java/com/growth/task/todo/repository/TodosRepositoryCustom.java, app-server/src/main/java/com/growth/task/todo/repository/impl/TodosRepositoryCustomImpl.java, app-server/src/main/resources/schema.sql, app-server/src/test/java/com/growth/task/task/service/TaskListServiceTest.java, app-server/src/test/java/com/growth/task/todo/application/TodoListServiceTest.java, app-server/src/test/java/com/growth/task/todo/controller/TodoListControllerTest.java
issue no. #216 
기본 페이징 : 사이즈 10 
정렬은 task_date 최신순으로 고정 -> 후에 동적 ordering으로 변경 필요
request param : size , page , status
response 리스트 형태 (투두 내용, 상태, 뽀모도로 개수, 테스크 날짜)
=> [Backend] 마이페이지 통계를 누르면 해당하는 리스트를 볼 수 있다#216

app-server/src/main/java/com/growth/task/review/domain/Review.java, app-server/src/main/java/com/growth/task/review/dto/ReviewAddRequest.java, app-server/src/main/java/com/growth/task/review/dto/ReviewDetailResponse.java, app-server/src/main/java/com/growth/task/review/dto/ReviewUpdateRequest.java, app-server/src/main/java/com/growth/task/review/repository/impl/ReviewRepositoryCustomImpl.java, app-server/src/test/java/com/growth/task/review/controller/ReviewAddControllerTest.java, app-server/src/test/java/com/growth/task/review/controller/ReviewDeleteControllerTest.java, app-server/src/test/java/com/growth/task/review/controller/ReviewDetailControllerTest.java, app-server/src/test/java/com/growth/task/review/controller/ReviewListControllerTest.java, app-server/src/test/java/com/growth/task/review/controller/ReviewUpdateControllerTest.java, app-server/src/test/java/com/growth/task/review/repository/ReviewRepositoryTest.java, app-server/src/test/java/com/growth/task/review/service/ReviewAddServiceTest.java, app-server/src/test/java/com/growth/task/review/service/ReviewDeleteServiceTest.java, app-server/src/test/java/com/growth/task/review/service/ReviewListServiceTest.java, app-server/src/test/java/com/growth/task/review/service/ReviewUpdateServiceTest.java, app-server/src/test/java/com/growth/task/task/controller/TaskListControllerTest.java
issue no. #236
회고에 오늘의 한 줄 컬럼 추가 
`subject varchar (50) not null`
추가, 삭제, 조회, 수정 로직에 subject 필드 추가
=> [Backend] 회고에서 오늘의 한 줄을 추가하라#236

app-client/src/components/Pomodoro/Pomodoro.tsx, app-client/src/pages/TodosPage/index.tsx
=> [Frontend] 뽀모도로 구현 구조 최적화하라

app-client/src/components/Stats/Mood/Chart.tsx, app-client/src/components/Stats/UI/Box.tsx, app-client/src/components/Stats/UI/Detail.tsx, app-client/src/components/Stats/UI/NavigationButtons.tsx, app-client/src/components/Stats/UI/Summary.tsx, app-client/src/pages/MyPage/index.tsx, app-client/src/services/mypage.ts, app-client/src/services/review.ts, app-client/src/store/mood.ts, app-client/src/store/stats.ts
=> [Frontend] 통계 감정 세부 리스트 API를 연동하라

app-client/src/components/Stats/Todos/Circle.tsx, app-client/src/components/Stats/UI/Detail.tsx, app-client/src/components/Stats/UI/NavigationButtons.tsx, app-client/src/pages/MyPage/index.tsx, app-client/src/services/mypage.ts, app-client/src/services/todo.ts, app-client/src/store/mood.ts, app-client/src/store/stats.ts, app-client/src/store/todos.ts
#251 
통계 할 일 세부 리스트 API연동, 페이징 구현
=> [Frontend] 통계 할 일 세부 리스트 API를 연동하라

app-client/src/components/Todos/TodoList.tsx, app-client/src/store/todos.ts
=> [Frontend] 새로고침시 할 일 개수 카운트 되지 않음

app-client/src/components/Stats/UI/Detail.tsx
=> [Frontend] 한 일 통계에서 날짜를 추가하라

app-client/src/components/Stats/UI/Detail.tsx
=> [Frontend] 통계 상세내용 클릭시 해당 날짜의 할 일 페이지로 이동하라

app-server/src/main/java/com/growth/task/review/dto/ReviewStatsResponse.java, app-server/src/main/java/com/growth/task/todo/dto/TodoResponse.java, app-server/src/main/java/com/growth/task/todo/dto/response/TodoDetailResponse.java
Json 응답시 스네이크 표기법 파싱 어노테이션 누락된 클래스에 명시. 
리스트 테스트 시, 사이즈만 검사하기 때문에 응답필드가 맞는지 확인하기 어려움
해당 테스트 작성하여 방지 -> 리스트 1건만 나오도록 테스트 목을 설정한다.
=> [Backend] Json 응답시 스네이크 표기법으로 파싱하라

app-client/src/components/Stats/UI/Detail.tsx, app-client/src/store/todos.ts
=> [Frontend] 스네이크 표기법으로 변경하라

app-server/src/main/java/com/growth/task/user/domain/Users.java, app-server/src/main/java/com/growth/task/user/domain/type/Role.java, app-server/src/main/java/com/growth/task/user/dto/LoginResponse.java, app-server/src/main/java/com/growth/task/user/dto/UserGetResponse.java, app-server/src/main/java/com/growth/task/user/dto/UserSignUpRequest.java, app-server/src/main/java/com/growth/task/user/dto/UserSignUpResponse.java, app-server/src/test/java/com/growth/task/mypage/controller/MyPageControllerTest.java, app-server/src/test/java/com/growth/task/pomodoro/controller/PomodoroUpdateControllerTest.java, app-server/src/test/java/com/growth/task/review/controller/ReviewAddControllerTest.java, app-server/src/test/java/com/growth/task/review/controller/ReviewDeleteControllerTest.java, app-server/src/test/java/com/growth/task/review/controller/ReviewDetailControllerTest.java, app-server/src/test/java/com/growth/task/review/controller/ReviewUpdateControllerTest.java, app-server/src/test/java/com/growth/task/review/repository/ReviewRepositoryTest.java, app-server/src/test/java/com/growth/task/task/controller/TaskAddControllerTest.java, app-server/src/test/java/com/growth/task/task/controller/TaskDeleteControllerTest.java, app-server/src/test/java/com/growth/task/task/controller/TaskDetailControllerTest.java, app-server/src/test/java/com/growth/task/task/controller/TaskListControllerTest.java, app-server/src/test/java/com/growth/task/task/repository/impl/TasksRepositoryCustomImplTest.java, app-server/src/test/java/com/growth/task/todo/controller/TodoAddControllerTest.java, app-server/src/test/java/com/growth/task/todo/controller/TodoDeleteControllerTest.java, app-server/src/test/java/com/growth/task/todo/controller/TodoListControllerTest.java, app-server/src/test/java/com/growth/task/todo/repository/TodosRepositoryTest.java, app-server/src/test/java/com/growth/task/user/controller/LoginControllerTest.java, app-server/src/test/java/com/growth/task/user/controller/UserControllerTest.java, app-server/src/test/java/com/growth/task/user/domain/UsersRepositoryTest.java
issue no. #217 
사용자 테이블에 role을 추가 
가입, 로그인, 조회시 role 항목도 보이도록 추가
=> [Backend] 사용자 권한을 추가하라 

app-client/src/components/Calendar/Calendar.tsx, app-client/src/components/Calendar/FeelingsScore.tsx, app-client/src/components/Review/UserReview.tsx, app-client/src/components/Stats/Todos/Circle.tsx, app-client/src/components/Stats/Todos/TodosStats.tsx, app-client/src/components/Stats/UI/Box.tsx, app-client/src/components/Stats/UI/Detail.tsx, app-client/src/components/Todos/DeleteTask.tsx, app-client/src/components/Todos/HeaderDate.tsx, app-client/src/components/Todos/TodoList.tsx, app-client/src/services/mypage.ts, app-client/src/services/review.ts, app-client/src/services/task.ts, app-client/src/services/todo.ts, app-client/src/services/users.ts, app-client/src/store/mood.ts, app-client/src/store/task.ts, app-client/src/store/todos.ts, app-client/src/utils/checkTaskExists.ts
이전에 스네이크로 들어오는 요청, 응답 값만 스네이크로 쓰거나 파싱 작업을 거치고 있던 것을 카멜로 통일
=> API request,response 응답값을 카멜 표기법로 통일하라

app-client/src/components/TaskTracking/TaskTracking.tsx, app-client/src/pages/TodosPage/index.tsx, app-client/src/utils/calculateTime.ts
=> [Frontend] 예정 시간, 남은 할 일, 완료한 시간, 완료한 한 일 추가하라

app-client/src/components/Todos/AddTodo.tsx, app-client/src/components/Todos/AddTodoTimer.tsx, app-client/src/components/Todos/AddTodoTimerList.tsx, app-client/src/components/Todos/DeleteTask.tsx, app-client/src/components/Todos/DeleteTodo.tsx, app-client/src/components/Todos/Header.tsx, app-client/src/components/Todos/HeaderDate.tsx, app-client/src/components/Todos/StateBtn.tsx, app-client/src/components/Todos/Todo.tsx, app-client/src/components/Todos/TodoDetail.tsx, app-client/src/components/UI/Modal.tsx, app-client/src/components/User/Login/LoginModal.tsx, app-client/src/hooks/useModal.ts, app-client/src/pages/MainPage/index.tsx, app-client/src/pages/TodosPage/index.tsx, app-client/src/store/guest.ts, app-client/src/utils/isGuest.ts
#275 
UX 개선
- 첫 화면 -> 투두 페이지 (로그인 없이 이용 가능)
- 로그인, 회원가입 상단에 버튼
=> [Frontend] 첫 화면을 할 일 페이지로 이동하라

app-client/src/utils/isGuest.ts
- 변경 전 : 로컬 스토리지에 해당 키의 값이 없을 경우에만 조건을 걸어두고 키가 아예 없을 때는 조건을 안 걸어놔서 Guest 접속이 안됐었음
- 변경 후 : userNameId가 없을 때도 Guest로 인식하도록 함.
todo 날짜와 현재 날짜가 맞는지 확인하는 로직도 추가
=> [Frontend] Guest 접속 안되는 현상 수정하라

app-client/src/components/Todos/Header.tsx, app-client/src/components/Todos/HeaderDate.tsx
#286 
todoPage의 header에
회원 : 마이페이지 / 달력보기
비회원 : 로그인 / 회원가입
각 다르기 표시하기
=> [Frontend] 로그인/ 회원가입 버튼 레이아웃 수정하라

app-client/src/components/Todos/AddTodo.tsx, app-client/src/components/Todos/Todo.tsx, app-client/src/pages/TodosPage/index.tsx
#280 
기존 할 일 텍스트의 최대길이 18 -> 50으로 늘림
해당 할 일 클릭 후 뜨는 좌측 타이틀은 한 줄로 보이도록 하고 한 줄이 넘어갈시 ... 처리
=> [Frontend] 할 일 텍스트의 최대 길이를 50으로 늘려라

app-client/index.html, app-client/src/hooks/useFavicon.ts
=> [Frontend] favicon 뜨지 않는 현상 수정하라

app-client/src/components/Todos/DeleteTask.tsx
=> [Frontend] 게스트 전체 삭제 기능 오류 수정하라

app-client/src/components/Todos/TodoList.tsx
할 일 선택 후 타이머 작동 중이 다른 할 일 클릭시 
'현재 타이머가 진행 중입니다. 정지 후 선택해주세요.' 창이 뜨도록 함.
=>  [Frontend] 할 일 선택 후 작동 중에 다른 할 일 클릭시 리셋되지 않도록 하라

app-client/src/components/Todos/AddTodo.tsx
#299 
할 일 입력 Input에 0.2rem 여백 부여
=> [Frontend] 할 일 input에 여백 부여하라

app-client/src/components/Todos/TodoDetail.tsx, app-client/tailwind.config.js
#301 
유저가 입력할 수 없는 disabled처리된 input은 회색 배경으로 처리하여 수정할 수 없는 input이라는 것을 보여줌
=> [Frontend] 완료 뽀모도로 개수를 수정할 수 없는 디자인으로 변경하라

app-client/src/components/Todos/DeleteAllTodos.tsx, app-client/src/components/Todos/TodoAllDelete.tsx
#303 
- 할 일 리스트가 존재할 때만 '전체 삭제하기' 텍스트가 뜨도록 변경
- 전체 삭제하기 클릭시 해당 테스크도 삭제되는 것이 아닌 모든 할 일만 삭제되도록 변경
=> [Frontend] 할 일이 없는 경우 빈 할 일 리스트를 수정하라

app-client/src/components/Todos/Todo.tsx, app-client/tailwind.config.js
#307 
할 일 완료시 회색 색상과 취소선 표시로 변경
+ tailwind css 불필요한 내용 삭제 및 수정
=> [Frontend] 할 일 완료 체크시 색상 연해지고 취소선 표시하라

app-client/src/components/Guide/Guide.tsx, app-client/src/components/Todos/AddTodo.tsx, app-client/src/components/Todos/DeleteTodo.tsx, app-client/src/components/Todos/TodoList.tsx, app-client/src/pages/TodosPage/index.tsx, app-client/src/services/todo.ts, app-client/src/store/guest.ts, app-client/src/store/todos.ts, app-client/src/utils/todosUpdateOrderNo.ts
#305 
할 일 리스트를 드래그하면 해당 할 일의 위치를 변경할 수 있다.
=> [Frontend] 할 일의 순서를 변경할 수 있도록 하라

app-client/src/components/Todos/Todo.tsx, app-client/src/components/Todos/TodoDetail.tsx
#315 
- 글자수 제한 변경
- 할 일 가운데 정렬 변경
=> [Frontend] 할 일 수정시 글자수 제한 50으로 변경하라

app-server/src/main/java/com/growth/task/category/controller/CategoryAddController.java, app-server/src/main/java/com/growth/task/category/controller/CategoryRetrieveController.java, app-server/src/main/java/com/growth/task/category/service/CategoryAddService.java, app-server/src/main/java/com/growth/task/category/service/CategoryRetrieveService.java, app-server/src/main/java/com/growth/task/global/error/ControllerErrorAdvice.java, app-server/src/test/java/com/growth/task/category/controller/CategoryRetrieveControllerTest.java, app-server/src/test/java/com/growth/task/category/service/CategoryRetrieveServiceTest.java
`GET /api/v1/categories` 
- 카테고리 리스트를 응답
=> [Backend] 카테고리 조회 api

app-server/src/main/java/com/growth/task/todo/domain/TodoCategory.java
투두 카테고리 연관테이블에 데이터 등록시 등록 시간 저장
수정시 수정시간 저장
=> [Backend] 투두 카테고리 연관테이블에 데이터 등록 및 수정시 날짜를 기록하라

app-server/src/main/java/com/growth/task/todo/dto/response/TodoWithPomodoroResponse.java, app-server/src/main/java/com/growth/task/todo/repository/impl/TodosRepositoryCustomImpl.java, app-server/src/test/java/com/growth/task/todo/controller/TodoListControllerTest.java, app-server/src/test/java/com/growth/task/todo/repository/TodosRepositoryTest.java
투두 리스트 조회 `/api/v1/todos` 
응답 값에 카테고리명 추가
=> [Backend] 투두 리스트 조회시 카테고리가 나오도록 하라

app-server/src/main/java/com/growth/task/todo/application/TodoCategoryUpdateService.java, app-server/src/main/java/com/growth/task/todo/application/TodoUpdateService.java, app-server/src/main/java/com/growth/task/todo/domain/TodoCategory.java, app-server/src/main/java/com/growth/task/todo/dto/request/TodoUpdateRequest.java, app-server/src/main/java/com/growth/task/todo/repository/TodoCategoryRepository.java, app-server/src/test/java/com/growth/task/todo/application/TodoCategoryUpdateServiceTest.java, app-server/src/test/java/com/growth/task/todo/application/TodoUpdateServiceTest.java, app-server/src/test/java/com/growth/task/todo/controller/TodoUpdateControllerTest.java
=> [Backend] 투두 API에서 카테고리를 추가하거나 수정하도록 하라

app-server/src/main/java/com/growth/task/todo/application/TodoCategoryDeleteService.java, app-server/src/main/java/com/growth/task/todo/controller/TodoDeleteController.java, app-server/src/main/java/com/growth/task/todo/repository/TodoCategoryRepository.java, app-server/src/test/java/com/growth/task/todo/controller/TodoDeleteControllerTest.java
api : DELETE `/api/v1/todos/{todoId}/category`
주어진 투두의 카테고리 제거
=> [Backend] 주어진 투두의 카테고리를 제거하는 API를 구현하고 테스트하라

app-client/src/components/Todos/AddCategory.tsx, app-client/src/components/Todos/AddTodo.tsx, app-client/src/components/Todos/Category.tsx, app-client/src/components/Todos/Header.tsx, app-client/src/components/Todos/TodoAllDelete.tsx, app-client/src/components/Todos/TodoList.tsx, app-client/src/services/category.ts, app-client/src/services/todo.ts, app-client/src/store/guest.ts, app-client/src/store/todos.ts
#328 
할 일을 카테고리별로 분류할 수 있도록 카테고리 기능 추가
=> [Frontend] 카테고리 기능을 추가하라

app-client/src/components/Todos/TodoList.tsx
#331 
카테고리별 보기를 클릭 후 의도하지 않은 버그 수정
=> [Frontend] 카테고리별 보기를 클릭한 후 할 일 리스트 변동시 전체보기로 되돌아가는 오류를 수정하라

app-client/src/components/Todos/Todo.tsx, app-client/src/components/Todos/TodoDetail.tsx, app-client/src/components/Todos/TodoList.tsx, app-client/src/services/todo.ts
#333 
할 일의 카테고리를 수정할 수 있다.
카테고리는 정해진 카테고리 목록 중에서만 선택할 수 있다.
=> [Frontend] 할 일의 카테고리를 수정할 수 있다.
